version: '3.3'

services:
  # Swagger API
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8801:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8802:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml
#    environment:
#      SWAGGER_JSON: /openapi.yaml

